// Teste da API REST - Funcionario

@baseURL = https://cadastro-funcionarios-gti.herokuapp.com
@id = 61539766dffe7fe747fd8ee0

###
// GET - Listar todas os cadastros
GEt {{baseURL}}/funcionarios
Content-Type: application/json

###
// GET - Listar todas as fucionario pelo id
GEt {{baseURL}}/funcionarios/{{id}}
Content-Type: application/json

###
// DELETE - Apaga um cadastro pelo id
DELETE {{baseURL}}/funcionarios/{{id}}
Content-Type: application/json

###
// POST - Incluir um novo cadastro
POST {{baseURL}}/funcionarios
Content-Type: application/json

{
    "nome": "Alice Girassol",
    "idade": "19",
    "genero": "Feminino",
    "profissao": "Professora",
    "status": "inativo"
}

###
// PUT - Altera um novo cadastro
PUT {{baseURL}}/funcionarios
Content-Type: application/json

{ "_id": "615ccd5c79703f837fead1a2",
    "nome": "Raquel Ribeiro da Silva",
    "idade": "59",
    "genero": "Feminino",
    "profissao": "Motorista D",
    "status": "inativo"
}